name: base-ubuntu-push

on:
  push:
    branches:
      - 'main'
    paths:
      - 'base/ubuntu/**'
      - '.github/workflows/base-ubuntu-push.yml'
  pull_request:
    branches: none
  schedule:
      - cron: '0 12 15 * *'
  workflow_dispatch:

env:
  image-names: |
        raiu/base-ubuntu
        ghcr.io/raiu/base-ubuntu


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHRC_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.image-names }}
          tags: latest


      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: base/ubuntu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
